competition_types:
  friendly:
    importance: 1
  nations_league:
    importance: 2
  continental_qualifier:
    importance: 3
  world_cup_qualifier:
    importance: 4
  continental_championship:
    importance: 5
  world_cup:
    importance: 6
